BookStore/BookStore_Core_Project/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BookStore_Core_Project.Controllers
{
    public class BooksController : Controller
    {
        public IActionResult Books()
        {
            return View();
        }
    }
}

BookStore/BookStore_Core_Project/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStore_Core_Project.Models;

namespace BookStore_Core_Project.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly MyContext _context;

        public CategoriesController(MyContext context)
        {
            _context = context;
        }

        // GET: Categories
        public IActionResult Index()
        {
            return View( _context.Categorys.ToList());
        }

      

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        
        public IActionResult Create(Category category)
        {
            
                _context.Add(category);
                 _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            
        }

        // GET: Categories/Edit/5
        public IActionResult Edit(int id)
        {
           

            var category =  _context.Categorys.Find(id);
         
            return View(category);
        }

        // POST: Categories/Edit/5
        
        [HttpPost]
        
        public IActionResult Edit(Category category)
        {
            

          
                    _context.Update(category);
                     _context.SaveChanges();
                
                return RedirectToAction(nameof(Index));
            
        }

        // GET: Categories/Delete/5
        public IActionResult Delete(int id)
        {
            var category = _context.Categorys.Find(id);
            _context.Categorys.Remove(category);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

BookStore/BookStore_Core_Project/Controllers/NewRealeaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BookStore_Core_Project.Controllers
{
    public class NewRealeaseController : Controller
    {
        public IActionResult New()
        {
            return View();
        }
    }
}

BookStore/BookStore_Core_Project/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BookStore_Core_Project.Controllers
{
    public class SearchController : Controller
    {
        public IActionResult Search()
        {
            return View();
        }
    }
}

BookStore/BookStore_Core_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore_Core_Project</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="~/css/templatemo_style.css" rel="stylesheet" type="text/css" />

    
    
</head>
<body>
    <div id="templatemo_container">
        <div id="templatemo_menu">

            <ul>
                <li><a asp-controller="Home" asp-action="Home">Home</a></li>
                <li><a asp-controller="BooksDataBase" asp-action="Index">BooksDataBase</a></li>
                <li><a asp-controller="Categories" asp-action="index">Add Categories</a></li>
                <li><a asp-controller="Search" asp-action="Search">Search</a></li>
                <li><a asp-controller="Books" asp-action="Books">Books</a></li>
                <li><a asp-controller="NewRealease" asp-action="New">New Realeases</a></li>
            </ul>
        </div>
        <div id="templatemo_header">
            <div id="templatemo_special_offers">
                <p>
                    <span>25%</span> discounts for
                    purchase over $80
                </p>
                <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
            </div>
            <div id="templatemo_new_books">
                <ul>
                    <li>Suspen disse</li>
                    <li>Maece nas metus</li>
                    <li>In sed risus ac feli</li>
                </ul>
                <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
            </div>
        </div>
    </div>

    <partial name="_CookieConsentPartial" />
    <div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - BookStore BIS</p>
        </footer>
    </div>
    @RenderSection("Scripts", required: false)


</body>
</html>